

Entities = {}

Entities.Objects = {
    [GetHashKey("prop_fnclink_05crnr1")] = true,
    [GetHashKey("xs_prop_hamburgher_wl")] = true,
    [GetHashKey("xs_prop_plastic_bottle_wl")] = true,
    [GetHashKey("prop_windmill_01")] = true,
    [GetHashKey("p_spinning_anus_s")] = true,
    [GetHashKey("stt_prop_ramp_adj_flip_m")] = true,
    [GetHashKey("stt_prop_ramp_adj_flip_mb")] = true,
    [GetHashKey("stt_prop_ramp_adj_flip_s")] = true,
    [GetHashKey("stt_prop_ramp_adj_flip_sb")] = true,
    [GetHashKey("stt_prop_ramp_adj_hloop")] = true,
    [GetHashKey("stt_prop_ramp_adj_loop")] = true,
    [GetHashKey("stt_prop_ramp_jump_l")] = true,
    [GetHashKey("stt_prop_ramp_jump_m")] = true,
    [GetHashKey("stt_prop_ramp_jump_s")] = true,
    [GetHashKey("stt_prop_ramp_jump_xl")] = true,
    [GetHashKey("stt_prop_ramp_jump_xs")] = true,
    [GetHashKey("stt_prop_ramp_jump_xxl")] = true,
    [GetHashKey("stt_prop_ramp_multi_loop_rb")] = true,
    [GetHashKey("stt_prop_ramp_spiral_l")] = true,
    [GetHashKey("stt_prop_ramp_spiral_l_l")] = true,
    [GetHashKey("stt_prop_ramp_spiral_l_m")] = true,
    [GetHashKey("stt_prop_ramp_spiral_l_s")] = true,
    [GetHashKey("stt_prop_ramp_spiral_l_xxl")] = true,
    [GetHashKey("stt_prop_ramp_spiral_m")] = true,
    [GetHashKey("stt_prop_ramp_spiral_s")] = true,
    [GetHashKey("stt_prop_ramp_spiral_xxl")] = true,
    [GetHashKey("stt_prop_stunt_track_dwuturn")] = true,
    [GetHashKey("stt_prop_stunt_track_dwslope30")] = true,
    [GetHashKey("stt_prop_stunt_track_start")] = true,
    [GetHashKey("stt_prop_stunt_track_hill2")] = true,
    [GetHashKey("stt_prop_stunt_bblock_huge_01")] = true,
    [GetHashKey("stt_prop_stunt_bblock_huge_02")] = true,
    [GetHashKey("stt_prop_stunt_bblock_huge_03")] = true,
    [GetHashKey("stt_prop_stunt_bblock_huge_04")] = true,
    [GetHashKey("stt_prop_stunt_bblock_huge_05")] = true,
    [GetHashKey("stt_prop_stunt_bblock_hump_01")] = true,
    [GetHashKey("stt_prop_stunt_bblock_hump_02")] = true,
    [GetHashKey("stt_prop_stunt_bblock_lrg1")] = true,
    [GetHashKey("stt_prop_stunt_bblock_lrg2")] = true,
    [GetHashKey("stt_prop_stunt_bblock_lrg3")] = true,
    [GetHashKey("stt_prop_stunt_bblock_mdm1")] = true,
    [GetHashKey("stt_prop_stunt_bblock_mdm2")] = true,
    [GetHashKey("stt_prop_stunt_bblock_mdm3")] = true,
    [GetHashKey("stt_prop_stunt_bblock_qp")] = true,
    [GetHashKey("stt_prop_stunt_bblock_qp2")] = true,
    [GetHashKey("stt_prop_stunt_bblock_qp3")] = true,
    [GetHashKey("prop_beach_fire")] = true,
    [GetHashKey("prop_gas_pump_1a")] = true,
    [GetHashKey("prop_gas_pump_1b")] = true,
    [GetHashKey("prop_gas_pump_1c")] = true,
    [GetHashKey("prop_gas_pump_1d")] = true,
    [GetHashKey("prop_gas_pump_old2")] = true,
    [GetHashKey("prop_gas_pump_old3")] = true,
    [GetHashKey("prop_vintage_pump")] = true,
    [GetHashKey("apa_mp_h_acc_box_trinket_01")] = true,
    [GetHashKey("prop_roundbailer02")] = true,
    [GetHashKey("prop_roundbailer01")] = true,
    [GetHashKey("prop_container_05a")] = true,
    [GetHashKey("stt_prop_stunt_bowling_ball")] = true,
    [GetHashKey("apa_mp_h_acc_rugwoolm_03")] = true,
    [GetHashKey("prop_container_ld2")] = true,
    [GetHashKey("p_ld_stinger_s")] = true,
    [GetHashKey("hei_prop_carrier_cargo_02a")] = true,
    [GetHashKey("p_cablecar_s")] = true,
    [GetHashKey("p_ferris_car_01")] = true,
    [GetHashKey("prop_cj_big_boat")] = true,
    [GetHashKey("prop_rock_4_big2")] = true,
    [GetHashKey("prop_steps_big_01")] = true,
    [GetHashKey("v_ilev_lest_bigscreen")] = true,
    [GetHashKey("prop_carcreeper")] = true,
    [GetHashKey("apa_mp_h_bed_double_09")] = true,
    [GetHashKey("apa_mp_h_bed_wide_05")] = true,
    [GetHashKey("prop_cattlecrush")] = true,
    [GetHashKey("prop_cs_documents_01")] = true,
    [GetHashKey("prop_ferris_car_01_lod1")] = true,
    [GetHashKey("prop_construcionlamp_01")] = true,
    [GetHashKey("prop_fncconstruc_01d")] = true,
    [GetHashKey("prop_fncconstruc_02a")] = true,
    [GetHashKey("p_dock_crane_cabl_s")] = true,
    [GetHashKey("prop_dock_crane_01")] = true,
    [GetHashKey("prop_dock_crane_02_cab")] = true,
    [GetHashKey("prop_dock_float_1")] = true,
    [GetHashKey("prop_dock_crane_lift")] = true,
    [GetHashKey("apa_mp_h_bed_double_08")] = true,
    [GetHashKey("csx_seabed_bldr4_")] = true,
    [GetHashKey("imp_prop_impexp_sofabed_01a")] = true,
    [GetHashKey("apa_mp_h_yacht_bed_01")] = true,
    [-685641702] = true, -- unknown
    [-1230672010] = true, -- unknown
    [-1404869155] = true, -- FBI Buildings
    [-759902142] = true, --Fire
}

Entities.Vehicles = {
    [GetHashKey("ardent")] = {name = "Ardent", bool = true},
    [GetHashKey("revolter")] = {name = "Revolter", bool = true},
    [GetHashKey("viseris")] = {name = "Viseris", bool = true},
    [GetHashKey("cargoplane")] = {name = "Cargo Plane", bool = true},
    [GetHashKey("dump")] = {name = "Dump", bool = true},
    [GetHashKey("avenger")] = {name = "Avenger", bool = true},
    [GetHashKey("avenger2")] = {name = "Avenger2", bool = true},
    [GetHashKey("luxor")] = {name = "Luxor", bool = true},
    [GetHashKey("khanjali")] = {name = "Khanjali", bool = true},
    [GetHashKey("rhino")] = {name = "Rhino", bool = true},
    [GetHashKey("insurgent")] = {name = "Insurgent", bool = true},
    [GetHashKey("insurgent3")] = {name = "Insurgent3", bool = true},
    [GetHashKey("oppressor")] = {name = "Oprresor", bool = true},
    [GetHashKey("oppressor2")] = {name = "Oprresor2", bool = true},
    [GetHashKey("maverick")] = {name = "Maverick", bool = true},
    [GetHashKey("blimp2")] = {name = "blimp2", bool = true},
    [GetHashKey("blimp")] = {name = "blimp", bool = true},
    [GetHashKey("blimp3")] = {name = "blimp3", bool = true},
    [GetHashKey("freight")] = {name = "Freight", bool = true},
    [GetHashKey("freightcar")] = {name = "FreightCar", bool = true},
    [GetHashKey("limo2")] = {name = "Limo2", bool = true},
    [GetHashKey("freightcont1")] = {name = "FreightCont1", bool = true},
    [GetHashKey("freightcont2")] = {name = "FreightCont2", bool = true},
    [GetHashKey("freightgrain")] = {name = "FreightGrain", bool = true},
    [GetHashKey("cerberus3")] = {name = "Cerberus3", bool = true},
    [GetHashKey("cerberus2")] = {name = "Cerberus2", bool = true},
    [GetHashKey("cerberus")] = {name = "Cerberus", bool = true},
    [GetHashKey("buzzard")] = {name = "Buzzard", bool = true},
    [GetHashKey("phantom2")] = {name = "Phantom2", bool = true},
    [GetHashKey("issi6")] = {name = "Issi6", bool = true},
    [GetHashKey("issi4")] = {name = "Issi4", bool = true},
    [GetHashKey("issi5")] = {name = "Issi5", bool = true},
    [GetHashKey("savage")] = {name = "Savage", bool = true},
    [GetHashKey("hunter")] = {name = "Hunter", bool = true},
    [GetHashKey("akula")] = {name = "Akula", bool = true},
    [GetHashKey("annihilator")] = {name = "Annihilator", bool = true},
    [GetHashKey("cutter")] = {name = "Cutter", bool = true},
    [GetHashKey("bulldozer")] = {name = "Bulldozer", bool = true},
    [GetHashKey("barracks")] = {name = "Barracks", bool = true},
    [GetHashKey("barracks2")] = {name = "Barracks2", bool = true},
    [GetHashKey("barracks3")] = {name = "Barracks3", bool = true},
    [GetHashKey("barrage")] = {name = "Barrage", bool = true},
    [GetHashKey("chernobog")] = {name = "Chernobog", bool = true},
    [GetHashKey("crusader")] = {name = "Crusader", bool = true},
    [GetHashKey("halftrack")] = {name = "HalfTrack", bool = true},
    [GetHashKey("minitank")] = {name = "MiniTank", bool = true},
    [GetHashKey("scarab")] = {name = "Scarab", bool = true},
    [GetHashKey("scarab2")] = {name = "Scarab2", bool = true},
    [GetHashKey("scarab3")] = {name = "Scarab3", bool = true},
    [GetHashKey("thruster")] = {name = "Thruster", bool = true},
    [GetHashKey("trailersmall2")] = {name = "Trailersmall2", bool = true},
    [GetHashKey("brutus3")] = {name = "Brutus3", bool = true},
    [GetHashKey("freecrawler")] = {name = "Freecrawler", bool = true},
    [GetHashKey("monster")] = {name = "Monster", bool = true},
    [GetHashKey("monster3")] = {name = "Monster3", bool = true},
    [GetHashKey("monster4")] = {name = "Monster4", bool = true},
    [GetHashKey("monster5")] = {name = "Monster5", bool = true},
    [GetHashKey("technical")] = {name = "Technical", bool = true},
    [GetHashKey("technical3")] = {name = "Technical3", bool = true},
    [GetHashKey("technical2")] = {name = "Technical2", bool = true},
    [GetHashKey("nightshark")] = {name = "Nightshark", bool = true},
    [GetHashKey("zhaba")] = {name = "Zhaba", bool = true},
    [GetHashKey("formula")] = {name = "Formula", bool = true},
    [GetHashKey("formula2")] = {name = "Formula2", bool = true},
    [GetHashKey("scramjet")] = {name = "Scramjet", bool = true},
    [GetHashKey("zr380")] = {name = "Zr380", bool = true},
    [GetHashKey("zr3802")] = {name = "Zr3802", bool = true},
    [GetHashKey("zr3803")] = {name = "Zr3803", bool = true},
    [GetHashKey("raptor")] = {name = "Raptor", bool = true},
    [GetHashKey("volatol")] = {name = "Volatol", bool = true},
    [GetHashKey("voltic2")] = {name = "Voltic2", bool = true},
    [GetHashKey("tula")] = {name = "Tula", bool = true},
    [GetHashKey("strikeforce")] = {name = "Strikeforce", bool = true},
    [GetHashKey("lazer")] = {name = "Lazer", bool = true},
    [GetHashKey("valkyrie2")] = {name = "Valkyrie2", bool = true},
    [GetHashKey("valkyrie")] = {name = "Valkyrie", bool = true},
    [GetHashKey("jet")] = {name = "Jet", bool = true},
    [GetHashKey("hydra")] = {name = "Hydra", bool = true},
    [GetHashKey("bombushka")] = {name = "Bombushka", bool = true},
    [GetHashKey("bruiser3")] = {name = "Bruiser3", bool = true},
    [GetHashKey("bruiser2")] = {name = "Bruiser2", bool = true},
    [GetHashKey("bruiser")] = {name = "Bruiser", bool = true},
    [GetHashKey("caracara")] = {name = "Caracara", bool = true},
    [GetHashKey("dune5")] = {name = "Dune5", bool = true},
    [GetHashKey("dune4")] = {name = "Dune4", bool = true},
    [GetHashKey("dune3")] = {name = "Dune3", bool = true},
    [GetHashKey("dune2")] = {name = "Dune2", bool = true},
    [GetHashKey("dune")] = {name = "Dune", bool = true},
    [GetHashKey("openwheel1")] = {name = "Openwheel1", bool = true},
    [GetHashKey("paragon2")] = {name = "Paragon2", bool = true},
    [GetHashKey("formula")] = {name = "Formula", bool = true},
    [GetHashKey("formula2")] = {name = "Formula2", bool = true},
    [GetHashKey("blazer5")] = {name = "Blazer5", bool = true},
    [GetHashKey("slamvan4")] = {name = "Slamvan4", bool = true},
    [GetHashKey("slamvan5")] = {name = "Slamvan5", bool = true},
    [GetHashKey("slamvan6")] = {name = "Slamvan6", bool = true},
    [GetHashKey("ruiner2")] = {name = "Ruiner2", bool = true},
    [GetHashKey("dukes2")] = {name = "Dukes2", bool = true},
    [GetHashKey("dominator4")] = {name = "Dominator4", bool = true},
    [GetHashKey("dominator5")] = {name = "Dominator5", bool = true},
    [GetHashKey("dominator6")] = {name = "Dominator6", bool = true},
    [GetHashKey("handler")] = {name = "Handler", bool = true},
    [GetHashKey("vindicator")] = {name = "Vindicator", bool = true},
    [GetHashKey("wastelander")] = {name = "Wastelander", bool = true},
    [GetHashKey("ardent")] = {name = "Ardent", bool = true},
    [GetHashKey("vigilante")] = {name = "Vigilante", bool = true},
    [GetHashKey("cargobob")] = {name = "Cargobob", bool = true},
}

Entities.Peds = {
    [GetHashKey("a_m_y_mexthug_01")] = {name = "MexThug", bool = true},
    [GetHashKey("a_c_husky")] = {name = "Huskey", bool = true}, 
    [GetHashKey("a_c_boar")] = {name = "Boar", bool = true}, 
    [GetHashKey("a_c_sharkhammer")] = {name = "Sharkhammer", bool = true}, 
    [GetHashKey("a_c_chimp")] = {name = "Chimp", bool = true}, 
    [GetHashKey("a_c_chop")] = {name = "Chop", bool = true}, 
    [GetHashKey("a_c_hen")] = {name = "Hen", bool = true}, 
    [GetHashKey("a_c_humpback")] = {name = "Humpback", bool = true}, 
    [GetHashKey("a_c_killerwhale")] = {name = "Killerwhale", bool = true},
    [GetHashKey("a_c_rhesus")] = {name = "Rhesus", bool = true}, 
    [GetHashKey("a_c_rottweiler")] = {name = "Rottweiler", bool = true}, 
    [GetHashKey("a_c_sharktiger")] = {name = "SharkTiger", bool = true}, 
    [GetHashKey("a_c_shepherd")] = {name = "Shepherd", bool = true}, 
    [GetHashKey("u_m_y_zombie_01")] = {name = "Zombie", bool = true},
    [GetHashKey("a_m_m_acult_01")] = {name = "Acult01", bool = true},
    [GetHashKey("u_m_y_juggernaut_01")] = {name = "Juggernaut", bool = true},
}