

            --- BEFORE STARTING PLEASE READ THIS MESSAGE
            --[[This file is the Entities config, Here you can setup the Entity Detection and the Anti Nuke detection for Peds/Objects and Vehicles... This feature got improved a lot, and we recommend using it]]
            -- If your vehicles are disappearing instantly, probably the antinuke or NONPC features are not for your server, disable these...

RS.EntitiesMasterSwitch = true
RS.EntitiesNONPC = false -- Enable this only if your server is a `NONPC` server (it blocks any kind of uncommon entity spawn)

    --(IMPORTANT!! If you are going to use WHITELISTED Method remember to edit your TABLES/Entities.lua table before starting the server)

    --Peds
    RS.EntitiesPedsDetection = true
    RS.EntitiesPedsKick = true
    RS.EntitiesPedsBan = true

    --Vehicles
    RS.EntitiesVehiclesDetection = true
    RS.EntitiesVehiclesKick = true
    RS.EntitiesVehiclesBan = true

    --Objects/Models
    RS.EntitiesObjectsMethod = 1 -- 1 FOR BLACKLISTED , 2 FOR WHITELISTED
    RS.EntitiesObjectsDetection = true
    RS.EntitiesObjectsKick = true
    RS.EntitiesObjectsBan = true

    --AntiNuke
    RS.EntitiesAntiNukePeds = true
    RS.EntitiesAntiNukeVehicles = true
    RS.EntitiesAntiNukeObjects = true
    RS.EntitiesAntiNukeSpawnLimit = 15 -- After 15 Spawned PEDS/VEH/OBJ the player gets automatically banned or warned
    RS.EntitiesAntiNukeResetTime = 8000 -- After 8 seconds the AntiNuke timer gets reseted


LynxEntities = {}

LynxEntities.Objects = {
    [GetHashKey("prop_fnclink_05crnr1")] = { name = "prop_fnclink_05crnr1" },
    [GetHashKey("xs_prop_hamburgher_wl")] = { name = "xs_prop_hamburgher_wl" },
    [GetHashKey("xs_prop_plastic_bottle_wl")] = { name = "xs_prop_plastic_bottle_wl" },
    [GetHashKey("prop_windmill_01")] = { name = "prop_windmill_01" },
    [GetHashKey("p_spinning_anus_s")] = { name = "p_spinning_anus_s" },
    [GetHashKey("stt_prop_ramp_adj_flip_m")] = { name = "stt_prop_ramp_adj_flip_m" },
    [GetHashKey("stt_prop_ramp_adj_flip_mb")] = { name = "stt_prop_ramp_adj_flip_mb" },
    [GetHashKey("stt_prop_ramp_adj_flip_s")] = { name = "stt_prop_ramp_adj_flip_s" },
    [GetHashKey("stt_prop_ramp_adj_flip_sb")] = { name = "stt_prop_ramp_adj_flip_sb" },
    [GetHashKey("stt_prop_ramp_adj_hloop")] = { name = "stt_prop_ramp_adj_hloop" },
    [GetHashKey("stt_prop_ramp_adj_loop")] = { name = "stt_prop_ramp_adj_loop" },
    [GetHashKey("stt_prop_ramp_jump_l")] = { name = "stt_prop_ramp_jump_l" },
    [GetHashKey("stt_prop_ramp_jump_m")] = { name = "stt_prop_ramp_jump_m" },
    [GetHashKey("stt_prop_ramp_jump_s")] = { name = "stt_prop_ramp_jump_s" },
    [GetHashKey("stt_prop_ramp_jump_xl")] = { name = "stt_prop_ramp_jump_xl" },
    [GetHashKey("stt_prop_ramp_jump_xs")] = { name = "stt_prop_ramp_jump_xs" },
    [GetHashKey("stt_prop_ramp_jump_xxl")] = { name = "stt_prop_ramp_jump_xxl" },
    [GetHashKey("stt_prop_ramp_multi_loop_rb")] = { name = "stt_prop_ramp_multi_loop_rb" },
    [GetHashKey("stt_prop_ramp_spiral_l")] = { name = "stt_prop_ramp_spiral_l" },
    [GetHashKey("stt_prop_ramp_spiral_l_l")] = { name = "stt_prop_ramp_spiral_l_l" },
    [GetHashKey("stt_prop_ramp_spiral_l_m")] = { name = "stt_prop_ramp_spiral_l_m" },
    [GetHashKey("stt_prop_ramp_spiral_l_s")] = { name = "stt_prop_ramp_spiral_l_s" },
    [GetHashKey("stt_prop_ramp_spiral_l_xxl")] = { name = "stt_prop_ramp_spiral_l_xxl" },
    [GetHashKey("stt_prop_ramp_spiral_m")] = { name = "stt_prop_ramp_spiral_m" },
    [GetHashKey("stt_prop_ramp_spiral_s")] = { name = "stt_prop_ramp_spiral_s" },
    [GetHashKey("stt_prop_ramp_spiral_xxl")] = { name = "stt_prop_ramp_spiral_xxl" },
    [GetHashKey("stt_prop_stunt_track_dwuturn")] = { name = "stt_prop_stunt_track_dwuturn" },
    [GetHashKey("stt_prop_stunt_track_dwslope30")] = { name = "stt_prop_stunt_track_dwslope30" },
    [GetHashKey("stt_prop_stunt_track_start")] = { name = "stt_prop_stunt_track_start" },
    [GetHashKey("stt_prop_stunt_track_hill2")] = { name = "stt_prop_stunt_track_hill2" },
    [GetHashKey("stt_prop_stunt_bblock_huge_01")] = { name = "stt_prop_stunt_bblock_huge_01" },
    [GetHashKey("stt_prop_stunt_bblock_huge_02")] = { name = "stt_prop_stunt_bblock_huge_02" },
    [GetHashKey("stt_prop_stunt_bblock_huge_03")] = { name = "stt_prop_stunt_bblock_huge_03" },
    [GetHashKey("stt_prop_stunt_bblock_huge_04")] = { name = "stt_prop_stunt_bblock_huge_04" },
    [GetHashKey("stt_prop_stunt_bblock_huge_05")] = { name = "stt_prop_stunt_bblock_huge_05" },
    [GetHashKey("stt_prop_stunt_bblock_hump_01")] = { name = "stt_prop_stunt_bblock_hump_01" },
    [GetHashKey("stt_prop_stunt_bblock_hump_02")] = { name = "stt_prop_stunt_bblock_hump_02" },
    [GetHashKey("stt_prop_stunt_bblock_lrg1")] = { name = "stt_prop_stunt_bblock_lrg1" },
    [GetHashKey("stt_prop_stunt_bblock_lrg2")] = { name = "stt_prop_stunt_bblock_lrg2" },
    [GetHashKey("stt_prop_stunt_bblock_lrg3")] = { name = "stt_prop_stunt_bblock_lrg3" },
    [GetHashKey("stt_prop_stunt_bblock_mdm1")] = { name = "stt_prop_stunt_bblock_mdm1" },
    [GetHashKey("stt_prop_stunt_bblock_mdm2")] = { name = "stt_prop_stunt_bblock_mdm2" },
    [GetHashKey("stt_prop_stunt_bblock_mdm3")] = { name = "stt_prop_stunt_bblock_mdm3" },
    [GetHashKey("stt_prop_stunt_bblock_qp")] = { name = "stt_prop_stunt_bblock_qp" },
    [GetHashKey("stt_prop_stunt_bblock_qp2")] = { name = "stt_prop_stunt_bblock_qp2" },
    [GetHashKey("stt_prop_stunt_bblock_qp3")] = { name = "stt_prop_stunt_bblock_qp3" },
    [GetHashKey("prop_beach_fire")] = { name = "prop_beach_fire" },
    [GetHashKey("prop_gas_pump_1a")] = { name = "prop_gas_pump_1a" },
    [GetHashKey("prop_gas_pump_1b")] = { name = "prop_gas_pump_1b" },
    [GetHashKey("prop_gas_pump_1c")] = { name = "prop_gas_pump_1c" },
    [GetHashKey("prop_gas_pump_1d")] = { name = "prop_gas_pump_1d" },
    [GetHashKey("prop_gas_pump_old2")] = { name = "prop_gas_pump_old2" },
    [GetHashKey("prop_gas_pump_old3")] = { name = "prop_gas_pump_old3" },
    [GetHashKey("prop_vintage_pump")] = { name = "prop_vintage_pump" },
    [GetHashKey("apa_mp_h_acc_box_trinket_01")] = { name = "apa_mp_h_acc_box_trinket_01" },
    [GetHashKey("prop_roundbailer02")] = { name = "prop_roundbailer02" },
    [GetHashKey("prop_roundbailer01")] = { name = "prop_roundbailer01" },
    [GetHashKey("prop_container_05a")] = { name = "prop_container_05a" },
    [GetHashKey("stt_prop_stunt_bowling_ball")] = { name = "stt_prop_stunt_bowling_ball" },
    [GetHashKey("apa_mp_h_acc_rugwoolm_03")] = { name = "apa_mp_h_acc_rugwoolm_03" },
    [GetHashKey("prop_container_ld2")] = { name = "prop_container_ld2" },
    [GetHashKey("p_ld_stinger_s")] = { name = "p_ld_stinger_s" },
    [GetHashKey("hei_prop_carrier_cargo_02a")] = { name = "hei_prop_carrier_cargo_02a" },
    [GetHashKey("p_cablecar_s")] = { name = "p_cablecar_s" },
    [GetHashKey("p_ferris_car_01")] = { name = "p_ferris_car_01" },
    [GetHashKey("prop_cj_big_boat")] = { name = "prop_cj_big_boat" },
    [GetHashKey("prop_rock_4_big2")] = { name = "prop_rock_4_big2" },
    [GetHashKey("prop_steps_big_01")] = { name = "prop_steps_big_01" },
    [GetHashKey("v_ilev_lest_bigscreen")] = { name = "v_ilev_lest_bigscreen" },
    [GetHashKey("prop_carcreeper")] = { name = "prop_carcreeper" },
    [GetHashKey("apa_mp_h_bed_double_09")] = { name = "apa_mp_h_bed_double_09" },
    [GetHashKey("apa_mp_h_bed_wide_05")] = { name = "apa_mp_h_bed_wide_05" },
    [GetHashKey("prop_cattlecrush")] = { name = "prop_cattlecrush" },
    [GetHashKey("prop_cs_documents_01")] = { name = "prop_cs_documents_01" },
    [GetHashKey("prop_ferris_car_01_lod1")] = { name = "prop_ferris_car_01_lod1" },
    [GetHashKey("prop_construcionlamp_01")] = { name = "prop_construcionlamp_01" },
    [GetHashKey("prop_fncconstruc_01d")] = { name = "prop_fncconstruc_01d" },
    [GetHashKey("prop_fncconstruc_02a")] = { name = "prop_fncconstruc_02a" },
    [GetHashKey("p_dock_crane_cabl_s")] = { name = "p_dock_crane_cabl_s" },
    [GetHashKey("prop_dock_crane_01")] = { name = "prop_dock_crane_01" },
    [GetHashKey("prop_dock_crane_02_cab")] = { name = "prop_dock_crane_02_cab" },
    [GetHashKey("prop_dock_float_1")] = { name = "prop_dock_float_1" },
    [GetHashKey("prop_dock_crane_lift")] = { name = "prop_dock_crane_lift" },
    [GetHashKey("apa_mp_h_bed_double_08")] = { name = "apa_mp_h_bed_double_08" },
    [GetHashKey("csx_seabed_bldr4_")] = { name = "csx_seabed_bldr4_" },
    [GetHashKey("imp_prop_impexp_sofabed_01a")] = { name = "imp_prop_impexp_sofabed_01a" },
    [GetHashKey("apa_mp_h_yacht_bed_01")] = { name = "apa_mp_h_yacht_bed_01" },
    [-685641702] = { name = "unknown" },
    [-1230672010] = { name = "unknown" },
    [-1404869155] = { name = "FIB Building" },
    [-759902142] = { name = "fire" },
}

LynxEntities.Vehicles = {
    [GetHashKey("cargoplane")] = {name = "Cargo Plane"},
    [GetHashKey("dump")] = {name = "Dump"},
    [GetHashKey("avenger")] = {name = "Avenger"},
    [GetHashKey("avenger2")] = {name = "Avenger2"},
    [GetHashKey("luxor")] = {name = "Luxor"},
    [GetHashKey("khanjali")] = {name = "Khanjali"},
    [GetHashKey("rhino")] = {name = "Rhino"},
    [GetHashKey("insurgent")] = {name = "Insurgent"},
    [GetHashKey("insurgent3")] = {name = "Insurgent3"},
    [GetHashKey("oppressor")] = {name = "Oprresor"},
    [GetHashKey("oppressor2")] = {name = "Oprresor2"},
    [GetHashKey("maverick")] = {name = "Maverick"},
    [GetHashKey("blimp2")] = {name = "blimp2"},
    [GetHashKey("blimp")] = {name = "blimp"},
    [GetHashKey("blimp3")] = {name = "blimp3"},
    [GetHashKey("freight")] = {name = "Freight"},
    [GetHashKey("freightcar")] = {name = "FreightCar"},
    [GetHashKey("limo2")] = {name = "Limo2"},
    [GetHashKey("freightcont1")] = {name = "FreightCont1"},
    [GetHashKey("freightcont2")] = {name = "FreightCont2"},
    [GetHashKey("freightgrain")] = {name = "FreightGrain"},
    [GetHashKey("cerberus3")] = {name = "Cerberus3"},
    [GetHashKey("cerberus2")] = {name = "Cerberus2"},
    [GetHashKey("cerberus")] = {name = "Cerberus"},
    [GetHashKey("buzzard")] = {name = "Buzzard"},
    [GetHashKey("phantom2")] = {name = "Phantom2"},
    [GetHashKey("issi6")] = {name = "Issi6"},
    [GetHashKey("issi4")] = {name = "Issi4"},
    [GetHashKey("issi5")] = {name = "Issi5"},
    [GetHashKey("savage")] = {name = "Savage"},
    [GetHashKey("hunter")] = {name = "Hunter"},
    [GetHashKey("akula")] = {name = "Akula"},
    [GetHashKey("annihilator")] = {name = "Annihilator"},
    [GetHashKey("cutter")] = {name = "Cutter"},
    [GetHashKey("bulldozer")] = {name = "Bulldozer"},
    [GetHashKey("barracks")] = {name = "Barracks"},
    [GetHashKey("barracks2")] = {name = "Barracks2"},
    [GetHashKey("barracks3")] = {name = "Barracks3"},
    [GetHashKey("barrage")] = {name = "Barrage"},
    [GetHashKey("chernobog")] = {name = "Chernobog"},
    [GetHashKey("crusader")] = {name = "Crusader"},
    [GetHashKey("halftrack")] = {name = "HalfTrack"},
    [GetHashKey("minitank")] = {name = "MiniTank"},
    [GetHashKey("scarab")] = {name = "Scarab"},
    [GetHashKey("scarab2")] = {name = "Scarab2"},
    [GetHashKey("scarab3")] = {name = "Scarab3"},
    [GetHashKey("thruster")] = {name = "Thruster"},
    [GetHashKey("trailersmall2")] = {name = "Trailersmall2"},
    [GetHashKey("brutus3")] = {name = "Brutus3"},
    [GetHashKey("freecrawler")] = {name = "Freecrawler"},
    [GetHashKey("monster")] = {name = "Monster"},
    [GetHashKey("monster3")] = {name = "Monster3"},
    [GetHashKey("monster4")] = {name = "Monster4"},
    [GetHashKey("monster5")] = {name = "Monster5"},
    [GetHashKey("technical")] = {name = "Technical"},
    [GetHashKey("technical3")] = {name = "Technical3"},
    [GetHashKey("technical2")] = {name = "Technical2"},
    [GetHashKey("nightshark")] = {name = "Nightshark"},
    [GetHashKey("zhaba")] = {name = "Zhaba"},
    [GetHashKey("formula")] = {name = "Formula"},
    [GetHashKey("formula2")] = {name = "Formula2"},
    [GetHashKey("scramjet")] = {name = "Scramjet"},
    [GetHashKey("zr380")] = {name = "Zr380"},
    [GetHashKey("zr3802")] = {name = "Zr3802"},
    [GetHashKey("zr3803")] = {name = "Zr3803"},
    [GetHashKey("raptor")] = {name = "Raptor"},
    [GetHashKey("volatol")] = {name = "Volatol"},
    [GetHashKey("voltic2")] = {name = "Voltic2"},
    [GetHashKey("tula")] = {name = "Tula"},
    [GetHashKey("strikeforce")] = {name = "Strikeforce"},
    [GetHashKey("lazer")] = {name = "Lazer"},
    [GetHashKey("valkyrie2")] = {name = "Valkyrie2"},
    [GetHashKey("valkyrie")] = {name = "Valkyrie"},
    [GetHashKey("jet")] = {name = "Jet"},
    [GetHashKey("hydra")] = {name = "Hydra"},
    [GetHashKey("bombushka")] = {name = "Bombushka"},
    [GetHashKey("bruiser3")] = {name = "Bruiser3"},
    [GetHashKey("bruiser2")] = {name = "Bruiser2"},
    [GetHashKey("bruiser")] = {name = "Bruiser"},
    [GetHashKey("caracara")] = {name = "Caracara"},
    [GetHashKey("dune5")] = {name = "Dune5"},
    [GetHashKey("dune4")] = {name = "Dune4"},
    [GetHashKey("dune3")] = {name = "Dune3"},
    [GetHashKey("dune2")] = {name = "Dune2"},
    [GetHashKey("dune")] = {name = "Dune"},
    [GetHashKey("openwheel1")] = {name = "Openwheel1"},
    [GetHashKey("paragon2")] = {name = "Paragon2"},
    [GetHashKey("formula")] = {name = "Formula"},
    [GetHashKey("formula2")] = {name = "Formula2"},
    [GetHashKey("blazer5")] = {name = "Blazer5"},
    [GetHashKey("slamvan4")] = {name = "Slamvan4"},
    [GetHashKey("slamvan5")] = {name = "Slamvan5"},
    [GetHashKey("slamvan6")] = {name = "Slamvan6"},
    [GetHashKey("ruiner2")] = {name = "Ruiner2"},
    [GetHashKey("dukes2")] = {name = "Dukes2"},
    [GetHashKey("dominator4")] = {name = "Dominator4"},
    [GetHashKey("dominator5")] = {name = "Dominator5"},
    [GetHashKey("dominator6")] = {name = "Dominator6"},
    [GetHashKey("handler")] = {name = "Handler"},
    [GetHashKey("vindicator")] = {name = "Vindicator"},
    [GetHashKey("wastelander")] = {name = "Wastelander"},
    [GetHashKey("ardent")] = {name = "Ardent"},
    [GetHashKey("vigilante")] = {name = "Vigilante"},
    [GetHashKey("cargobob")] = {name = "Cargobob"},
}

LynxEntities.Peds = {
    [GetHashKey("a_m_y_mexthug_01")] = {name = "MexThug"},
    [GetHashKey("a_c_husky")] = {name = "Huskey"}, 
    [GetHashKey("a_c_boar")] = {name = "Boar"}, 
    [GetHashKey("a_c_sharkhammer")] = {name = "Sharkhammer"}, 
    [GetHashKey("a_c_chimp")] = {name = "Chimp"}, 
    [GetHashKey("a_c_chop")] = {name = "Chop"}, 
    --[GetHashKey("a_c_hen")] = {name = "Hen"}, 
    [GetHashKey("a_c_humpback")] = {name = "Humpback"}, 
    [GetHashKey("a_c_killerwhale")] = {name = "Killerwhale"},
    [GetHashKey("a_c_rhesus")] = {name = "Rhesus"}, 
    [GetHashKey("a_c_rottweiler")] = {name = "Rottweiler"}, 
   -- [GetHashKey("a_c_sharktiger")] = {name = "SharkTiger"}, 
    [GetHashKey("a_c_shepherd")] = {name = "Shepherd"}, 
    [GetHashKey("u_m_y_zombie_01")] = {name = "Zombie"},
    [GetHashKey("a_m_m_acult_01")] = {name = "Acult01"},
    [GetHashKey("u_m_y_juggernaut_01")] = {name = "Juggernaut"},
}